version: "3.9"
services:
  postgres:
    build: .
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./src:/src
#  redis:
#    image: "redis:alpine"
#    ports:
#      - "6379:6379"
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.4
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=postgres
      - DB_USER=postgres
      - DB_PASSWORD=password
    ports:
      - "8080:8080"
  postgrest:
    image: "postgrest/postgrest:v7.0.1"
    ports:
      - "3000:3000"
    environment:
      - PGRST_DB_URI=postgres://postgres:password@postgres/
      - PGRST_DB_ANON_ROLE=postgres
      - PGRST_DB_SCHEMA=api,
